# Generated by Django 3.1.3 on 2021-01-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educator', '0003_auto_20210124_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(null=True)),
                ('date_to', models.DateTimeField(null=True)),
                ('leave_type', models.CharField(choices=[('Annual', 'Annual'), ('Sick', 'Sick'), ('Personal', 'Personal'), ('No pay', 'No pay'), ('Parental', 'Parental'), ('Other', 'Other')], max_length=200, null=True)),
                ('leave_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('educator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educator.educator')),
            ],
            options={
                'verbose_name': 'Leave',
                'verbose_name_plural': 'Leaves',
            },
        ),
    ]
