# Generated by Django 3.1.3 on 2021-01-25 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0003_auto_20210124_0832'),
        ('leave', '0002_auto_20210125_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='educator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='educator.educator'),
        ),
    ]
