# Generated by Django 3.1.3 on 2021-01-23 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        ('educator', '0002_remove_educator_nick_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('shift_start_time', models.TimeField(default='00:00', null=True)),
                ('shift_end_time', models.TimeField(default='12:00', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], max_length=200, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('educator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educator.educator')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.manager')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
