# Generated by Django 3.1.3 on 2021-01-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educator', '0003_auto_20210124_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(default='06:30', null=True)),
                ('end_time', models.TimeField(default='18:30', null=True)),
                ('educator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educator.educator')),
            ],
            options={
                'verbose_name': 'Availabile',
                'verbose_name_plural': 'Availability',
            },
        ),
    ]
