# Generated by Django 3.1.3 on 2021-01-23 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(default='no_nickname', max_length=200, null=True)),
                ('mobile', models.IntegerField(default=0, null=True)),
                ('qualification', models.CharField(choices=[('Working Towards Cert III', 'Working Towards Cert III'), ('Cert III', 'Cert III'), ('Working Towards Diploma', 'Working Towards Diploma'), ('Diploma', 'Diploma'), ('Working Towards Degree', 'Working Towards Degree'), ('Degree', 'Degree'), ('Working Towards Master Degree', 'Working Towards Master Degree'), ('Master Degree', 'Master Degree'), ('Others', 'Others')], max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('room', models.CharField(blank=True, choices=[('Baby Room 0 - 12', 'Baby Room 0 - 12'), ('Toddlers Room 12 - 18', 'Toddlers Room 12 - 18'), ('Support Staff', 'Support Staff')], max_length=200, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Educator',
                'verbose_name_plural': 'Educators',
            },
        ),
    ]
