# Generated by Django 3.1.3 on 2021-01-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educator',
            name='nick_name',
        ),
    ]
