# Generated by Django 3.1.3 on 2021-01-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0002_remove_educator_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='profiles'),
        ),
    ]
