# Generated by Django 3.1.3 on 2021-01-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0003_auto_20210124_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='pin',
            field=models.CharField(default='1234', max_length=4, null=True),
        ),
    ]
