# Generated by Django 3.1.3 on 2021-01-23 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('shift_start_time', models.TimeField(default='00:00', null=True)),
                ('shift_end_time', models.TimeField(default='12:00', null=True)),
                ('qualification', models.CharField(choices=[('Cert III or above', 'Cert III or above'), ('Diploma or above', 'Diploma or above')], default='Cert III or above', max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.manager')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
