# Generated by Django 3.1.3 on 2021-01-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(choices=[('Working Towards Cert III', 'Working Towards Cert III'), ('Cert III', 'Cert III'), ('Working Towards Diploma', 'Working Towards Diploma'), ('Diploma', 'Diploma'), ('Working Towards Degree', 'Working Towards Degree'), ('Degree', 'Degree'), ('Working Towards Master Degree', 'Working Towards Master Degree'), ('Master Degree', 'Master Degree'), ('Others', 'Others')], default='Cert III or above', max_length=200, null=True),
        ),
    ]
