# Generated by Django 3.1.3 on 2021-01-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_start',
            field=models.DateTimeField(null=True),
        ),
    ]
