# Generated by Django 3.1.4 on 2021-01-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0002_auto_20210125_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
