# Generated by Django 3.1.4 on 2021-02-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0003_auto_20210130_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
